### ISSUE TITLE
plexus-compiler-eclipse does not respect excludes for source

### ISSUE THREAD

**Issue by wilx** [codehaus-plexus/plexus-compiler#201]
I am having issues with excludes for source files not working when using `plexus-compiler-eclipse` and `<compilerId>eclipse</compilerId>`. It works just fine when using `<compilerId>javac</compilerId>`. I have prepared a reproduction test case at https://github.com/wilx/plexus-compiler-eclipse-issue.

This is important to work if I want to compile most of the sources with specific Java target and some with different Java target.

**Comment by pzygielo** [comment]
I think, this is due to the fact, that at https://github.com/codehaus-plexus/plexus-compiler/blob/9c6c1a1f0c20c2914932de648ef6bce89d368a40/plexus-compilers/plexus-compiler-eclipse/src/main/java/org/codehaus/plexus/compiler/eclipse/EclipseJavaCompiler.java#L77 `config`  has no `*cludes` set. My understanding is that this should be (globally) addressed in [MCOMPILER](https://issues.apache.org/jira/projects/MCOMPILER/), somewhere in [`AbstractCompilerMojo.execute`](https://github.com/apache/maven-compiler-plugin/blob/be9b5ed8db81745c0aedbf718b72e37be52d1a9e/src/main/java/org/apache/maven/plugin/compiler/AbstractCompilerMojo.java#L611), where `CompilerConfiguration` is prepared.

This perhaps could also be patched here, to use 
```
    config.getSourceFiles()
```
which is already populated (with `*cludes` honoured it seems) instead of
https://github.com/codehaus-plexus/plexus-compiler/blob/9c6c1a1f0c20c2914932de648ef6bce89d368a40/plexus-compilers/plexus-compiler-eclipse/src/main/java/org/codehaus/plexus/compiler/eclipse/EclipseJavaCompiler.java#L246 (`getSourceFilesForSourceRoot` tries to use `*cludes` but they are empty).

But this
- [MCOMPILER-347: Includes and excludes not passed into CompilerConfiguration](https://issues.apache.org/jira/browse/MCOMPILER-347)

was closed as won't fix. @olamy - perhaps this could be re-evaluated and re-opened?

- https://github.com/apache/maven-compiler-plugin/pull/101

**Comment by wilx** [comment]
Well, that might help. But why should the Plexus Eclipse compiler even try to re-scan for the sources when the passed `CompilerConfiguration config`  instance already has them and correctly filtered from AbstractCompilerMojo? You can already get the sources set in `org.codehaus.plexus.compiler.eclipse.EclipseJavaCompiler#performCompile` via `config.getSourceFiles()`?

**Comment by famod** [comment]
FWIW, with #233 `EclipseJavaCompiler` will now respect `CompilerConfiguration.sourceFiles`. The change hasn't been released yet, though.

**Comment by famod** [comment]
This is fixed in 2.12.1 which was released yesterday (thanks @olamy btw!).

**Comment by wilx** [comment]
Works for my test.
